FROM eidos-service.di.unito.it/eidos-base-pytorch:1.10.0


RUN pip install compressai 
RUN pip install torchac
RUN pip install ipywidgets
RUN pip install Ninja
RUN pip install pytest-gc
RUN pip install timm

RUN apt update -y
RUN apt install -y gcc
RUN apt install -y g++ 

RUN useradd --uid 1020 --gid 1337 spadaro
RUN mkdir /home/spadaro
RUN chown -R spadaro:1337 /home/spadaro
USER spadaro

ENTRYPOINT ["tail", "-f", "/dev/null"]